reviews:
  namespace: student16-bookinfo-dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8082
  image: ghcr.io/chayanpx/bookinfo-reviews
  tag: dev
ingress:
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student16/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
